---
# Node Count
number_of_swarm_masters: 3
number_of_swarm_nodes: 3

# Node Size
cf_swarm_master_instance_type: t2.nano
cf_swarm_node_instance_type: t2.nano

# Security
cf_allowed_swarm_master_control_from: 0.0.0.0/0
cf_allowed_etcd_discovery_from: 0.0.0.0/0
advertised_ip_address: private

### Secure Cluster Only
# Logs (aws uses cloudwatch, any other string will use the default driver)
swarm_logs: aws
log_group: swarm

# Service Discovery (etcd or consul)
swarm_discovery: consul

# Cert Info
certificate_country: US
certificate_state: TX
certificate_locality: DFW 
certificate_ou: Boss
