---

- name: Get a new Discovery Service url
  uri:
    url: "https://discovery.etcd.io/new?size={{ cf_master_cluster_size }}"
    return_content: yes
  register: discovery_service_url

- set_fact:
    master_cloud_config: "{{ lookup('template', 'cloud-init-master.yml') | replace('\r\n', '\\n') }}"
    node_cloud_config: "{{ lookup('template', 'cloud-init-node.yml') | replace('\r\n', '\\n') }}"

- set_fact:    
    cf_template: "{{ lookup('template', 'secure-swarm-base.json') }}"

- name: Save the generated CF template file
  local_action: copy content="{{ cf_template }}" dest=./cf_template

- name: Create a new Stack using the given params and template
  cloudformation:
    state: "present"
    stack_name: "{{ cf_stack_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    template: "cf_template"
    region: "{{ cf_region }}"
    template_parameters:
      AllowSwarmMasterControlFrom: "{{ cf_allowed_swarm_master_control_from }}"
      AllowEtcdDiscoveryFrom: "{{ cf_allowed_etcd_discovery_from }}"
      DiscoveryURL: "{{ discovery_service_url.content }}"
      MasterInstanceType: "{{ cf_swarm_master_instance_type }}"
      MasterClusterSize: "{{ number_of_swarm_masters }}"
      NodeInstanceType: "{{ cf_swarm_node_instance_type }}"
      NodeClusterSize: "{{ number_of_swarm_nodes }}"
      KeyName: "{{ aws_keypair }}"
      VpcAvailabilityZones: "{{ cf_vpc_azs }}"
    tags:
      Stack: "ansible-cloudformation"
      Owner: "{{ aws_owner }}"
  register: stack_creation_response