#cloud-config

coreos:
  etcd2:
    discovery: {{ discovery_service_url.content }}
    advertise-client-urls: http://${{ advertised_ip_address }}_ipv4:2379
    initial-advertise-peer-urls: http://${{ advertised_ip_address }}_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://${{ advertised_ip_address }}_ipv4:2380
units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
      drop-ins:
            - name: 10-docker.conf
              content: |
                [Service]
                Environment=\"DOCKER_OPTS=-H unix:///var/run/docker.sock\"
    - name: couchbase.service
      command: start
      content: |
        [Unit]
        Description=Couchbase service
        After=docker.service

        [Service]
        Restart=no
        ExecStart=/usr/bin/docker run -d -p 8091:8091 -p 8092:8092 -p 11207:11207 -p 11210:11210 -p 11211:11211 -p 11214:11214 -p 11215:11215 -p 18091:18091 -p 18092:18092 -v /home/core/couchbase:/opt/couchbase/var --net=host couchbase:community-4.0.0