---

- name: Get Fact for Node Cert Conf
  set_fact:
    node_open_ssl_conf: "{{ lookup('template', 'openssl.cnf', convert_data=False) }}"
  
- name: Creates directory
  file: path=./certs state=directory

- name: Save openssl.conf
  local_action: copy content="{{ node_open_ssl_conf }}" dest=./certs/openssl.conf

- name: Create our private CA Key
  shell: openssl genrsa -out CAkey.pem 2048 chdir=certs/
           
- name: Sign CA Certificate
  shell: openssl req -config openssl.conf -new -key CAkey.pem -x509 -days 3650 -out ca.pem chdir=certs/
  
- name: Copy Cert Script into place
  local_action: copy src=./roles/certs/create_certs/files/create-cert.sh dest=./certs/create-cert.sh mode=777

- name: Create Node Certs
  shell: "./create-cert.sh {{ item }} chdir=certs/"
  with_items: groups.launched