---

- name: Get a new Discovery Service url
  uri:
    url: "https://discovery.etcd.io/new?size={{ number_of_nodes }}"
    return_content: yes
  register: discovery_service_url

- set_fact:
    cloud_config: "{{ lookup('template', '../templates/cloud-init.yml') | replace('\r\n', '\\n') }}"

- set_fact:
    cf_template: "{{ lookup('template', 'couchbase-coreos-hvm.template') }}"

- name: Save the generated CF template file
  local_action: copy content="{{ cf_template }}" dest=./cf_template

- name: Create a new Stack using the given params and template
  cloudformation:
    state: "present"
    stack_name: "{{ cf_stack_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    template: "cf_template"
    region: "{{ cf_region }}"
    template_parameters:
      AllowDiscoveryFrom: "{{ cf_allowed_etcd_discovery_from }}"
      DiscoveryURL: "{{ discovery_service_url.content }}"
      InstanceType: "{{ cf_instance_type }}"
      ClusterSize: "{{ number_of_nodes }}"
      KeyName: "{{ aws_keypair }}"
      VpcAvailabilityZones: "{{ cf_vpc_azs }}"
    tags:
      Stack: "ansible-cloudformation"
      Owner: "{{ aws_owner }}"
  register: stack_creation_response

- name: Stack Output
  debug: msg="{{ stack_creation_response.stack_outputs }}"
