---

- set_fact:
    node_open_ssl_conf: "{{ lookup('template', 'openssl.cnf', convert_data=False) }}"
    swarm_open_ssl_conf: "{{ lookup('template', 'swarm-openssl.cnf', convert_data=False) }}"

- name: Creates directory
  file: path=./certs state=directory

- name: Save openssl.conf
  local_action: copy content="{{ node_open_ssl_conf }}" dest=./certs/openssl.conf

- name: Create our private CA Key
  shell: openssl genrsa -out CAkey.pem 2048 chdir=certs/
         
- name: Sign CA Certificate
  shell: openssl req -config openssl.conf -new -key CAkey.pem -x509 -days 3650 -out ca.pem chdir=certs/

- name: Copy Cert Script into place
  local_action: copy src=./roles/common/certs/create_certs/files/create_cert.sh dest=./certs/create_cert.sh mode=777

- name: Create Node Certs
  shell: "./create_cert.sh {{ item }} chdir=certs/"
  with_items: groups.launched

- name: Save openssl.conf
  local_action: copy content="{{ swarm_open_ssl_conf }}" dest=./certs/openssl.conf
  
- name: Create Swarm Cert
  shell: "./create_cert.sh {{ master_lb }} chdir=certs/"
