---

- hosts: localhost
  connection: local
  roles:
  - aws/create_swarm_base
  - aws/facts/set_swarm

- hosts: launched
  remote_user: core
  gather_facts: False
  roles:
  - defunctzombie.coreos-bootstrap
  
- hosts: first_master
  remote_user: core
  sudo: True
  roles:
  - common/swarm/init_swarm
  
- hosts: other_masters
  remote_user: core
  sudo: True
  roles:
  - common/swarm/configure_master

- hosts: worker_nodes
  remote_user: core
  sudo: True
  roles:
  - common/swarm/configure_worker  
  
- hosts: localhost
  connection: local
  tasks:
  - name: Print Swarm masters
    debug: msg="{{ item }}"
    with_items: groups.master_nodes  
  - name: Print App Nodes
    debug: msg="{{ item }}"
    with_items: groups.worker_nodes