---

- hosts: localhost
  connection: local
  tasks:
  - name: Provision a set of instances
    ec2:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       key_name: "{{ workshop_key }}"
       group: "{{ workshop_sg }}"
       instance_type: "{{ workshop_instance_size }}"
       image: "{{ workshop_ami_id }}"
       wait: true
       exact_count: "{{ workshop_count }}"
       count_tag:
          Name: Workshop
       instance_tags:
          Name: Workshop
    register: ec2
