---

- hosts: localhost
  connection: local
  tasks:
  - name: Generate secrets
    set_fact:
      secrets: "{{ (1 | generate_uuid) }}"
  - name: Set secrets
    set_fact:
      master_acl: "{{ secrets.0 }}"

# TODO: Install docker in cloud_init
     
- hosts: consul_master
  roles:
  - consul/provision_first_master

- hosts: other_masters
  roles:
  - consul/provision_master  

- hosts: localhost 
  connection: local 
  roles: 
  - consul/configure_acl 