  
- name: Get Master Nodes Info
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ cf_region }}"
    filters:
      instance-state-name: running
      "tag:CouchbaseRole": Master
  register: couchbase_masters

- name: Get Data Nodes Info
  ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ cf_region }}"  
    filters:
      instance-state-name: running
      "tag:CouchbaseRole": Data
  register: couchbase_data

- set_fact:
    master_ip="{{lookup('dig', couchbase_masters.instances[0].public_dns_name)}}"
    other_master_private_ips="{% for item in couchbase_masters.instances %}{% if not loop.first %}[ '{{ item.private_ip_address }}' ]{% if not loop.last %} + {% endif %}{% endif %}{% endfor%}"
    other_master_ips="{% for item in couchbase_masters.instances %}{% if not loop.first %}[ '{{lookup('dig', item.public_dns_name)}}' ]{% if not loop.last %} + {% endif %}{% endif %}{% endfor%}"    
    data_private_ips="{% for item in couchbase_data.instances %}[ '{{ item.private_ip_address }}' ]{% if not loop.last %} + {% endif %}{% endfor%}"  
    data_ips="{% for item in couchbase_data.instances %}[ '{{lookup('dig', item.public_dns_name)}}' ]{% if not loop.last %} + {% endif %}{% endfor%}"  